### ISSUE TITLE
Demo crash when discovering resources from Ostro image#507 

### ISSUE THREAD

**Issue by qiuzhong** [01org/cordova-plugin-ocf#2]
Steps:
1. Deploy the latest [SmartHome-Demo](https://github.com/01org/SmartHome-Demo) to the edison device flashed with latest image#507 
2. Create OCF resources via the SmartHome-Demo JavaScript OCF server
3. Try to build an OCF client [smart-home-control](https://github.com/siovene/smart-home-control) with this plugin to find the resources.

The client crashed during discovering the resources. The attachment is the log when the client was crashing. Another [cordova-plugin-ocf-demo](https://github.com/siovene/cordova-plugin-ocf-demo) also crashed when discovering the resources.

In Ostro image#507, the iotivity version is 1.1.1. The latest [SmartHome-Demo](https://github.com/01org/SmartHome-Demo) requires iotivity-node 1.1.1-3.

In [cordova-plugin-ocf-demo README](https://github.com/siovene/cordova-plugin-ocf-demo/blob/master/README.md), it says currently this plugin ships with pre-built Iotivity 1.0.1

I guess this crash is caused by the mismatch iotivity version between the OCF client and the server.
Any solution to fix this issue?

Attchment:
[smart-home-control-crash.txt](https://github.com/01org/cordova-plugin-ocf/files/523705/smart-home-control-crash.txt)

**Comment by wanghongjuan** [comment]
Hi, @poussa could you please ask someone to take a look at this? It blocks demo testing.

**Comment by siovene** [comment]
Iotivity 1.0.1 is not compatible with 1.1.1. I will update this plugin to use 1.1.1 too.

**Comment by siovene** [comment]
Should now be fixed with the release of v0.6.1.
